export const ActionTypes = {
    GET_CLASSES: "GET_CLASSES",
    GET_USERDATA:"GET_USERDATA",
    UPDATE_COUNSELLOR:"UPDATE_COUNSELLOR",
    GET_ALL_STUDENT_DATA:"GET_ALL_STUDENT_DATA",
    SEARCH_KEYWORD:"SEARCH_KEYWORD",
    RESET_PASSWORD:"RESET_PASSWORD",
    UPDATE_STUDENT:"UPDATE_STUDENT",
  
  };