export const csvData = [
    { 
        assignClass:"Class A",
        name:"Max",
        lastName:"Proton",  
        fatherName:"Jason",
        DOB:"2020/07/09",
        street_Address:"64 A scheme no. washingtone",
        city:'new york',
        zip_code:'54654',
        country:'USA',
        state:'Colorado',
        medical:" Neurology and Neurosurgery",
        emergency_name_1:"Grand Father",
        emergency_num_1:1234567898,
        emergency_name_2:"Grand Mother",
        emergency_num_2:1234543215,
        image:"https://cdn.pixabay.com/photo/2013/07/18/20/26/sea-164989_640.jpg"
    },
    {   
        assignClass:"",
        name:"",
        lastName:"",
        fatherName:"",
        DOB:"",
        street_Address:"",
        city:'',
        zip_code:'',
        country:'',
        state:'',
        medical:"",
        emergency_name_1:"",
        emergency_num_1:"",
        emergency_name_2:"",
        emergency_num_2:"",
        image:""},
   
  ];