export const csvData = [
    {   
        assignClass:"class B",
        name:"Jhon",
        lastName:"Hyler",
        fatherName:"Jimmy",
        DOB:'2003/07/16',
        address:"44 A scheme no. newyork",
        medical:"Last 2 years i am suffering from cancer" ,
        emergency_name_1:"Father",
        emergency_num_1:1234567898,
        emergency_name_2:"Mother",
        emergency_num_2:1234543215,
        emergency_name_3:"Sister",
        emergency_num_3:5432568964,
        image:"https://cdn.pixabay.com/photo/2013/07/18/20/26/sea-164989_640.jpg"
    },
    { 
        assignClass:"class C",
        name:"Max",
        lastName:"Proton",  
        fatherName:"Jason",
        DOB:"'2013/07/09",
        address:"64 A scheme no. washingtone",
        medical:" Neurology and Neurosurgery",
        emergency_name_1:"Grand Father",
        emergency_num_1:1234567898,
        emergency_name_2:"Grand Mother",
        emergency_num_2:1234543215,
        emergency_name_3:"Sister",
        emergency_num_3:5432568964,
        image:"https://cdn.pixabay.com/photo/2013/07/18/20/26/sea-164989_640.jpg"
    },
    {   
        assignClass:"",
        name:"",
        lastName:"",
        fatherName:"",
        DOB:"",
        address:"",
        medical:"",
        emergency_name_1:"",
        emergency_num_1:"",
        emergency_name_2:"",
        emergency_num_2:"",
        emergency_name_3:"",
        emergency_num_3:"",
        image:""},
   
  ];